enum ActionType {
  GET_USER_ROOMS_START = 'GET_USER_ROOM_START',
  GET_USER_ROOMS_SUCCESS = 'GET_USER_ROOM_SUCCESS',
  GET_USER_ROOMS_ERROR = 'GET_USER_ROOM_ERROR',
  REMOVE_USER_ROOMS = 'REMOVE_USER_ROOMS',
}

export default ActionType;
