enum ActionType {
  GET_ROOM_DETAILS_START = 'GET_ROOM_DETAILS_START',
  GET_ROOM_DETAILS_SUCCESS = 'GET_ROOM_DETAILS_SUCCESS',
  GET_ROOM_DETAILS_ERROR = 'GET_ROOM_DETAILS_ERROR',
}

export default ActionType;
